package com.chess.core;

public class AppConstants {
	public static String ENTER_FROM_NOTIFICATION = "enter_from_notification";
	public static String GAME_ID = "game_id";
	public static String TIMESTAMP = "time_stamp";
	public static String GAME_MODE = "game_mode";
	public static String MESSAGE = "message";
	public static String FINISHABLE = "finishable";
	public static String LIVE_CHESS = "live_chess";
	public static String OBJECT = "object";
	public static String TITLE = "title";
	public static String TAB_INDEX	= "tab_index";
	public static String VIDEO_SKILL_LEVEL = "video_skill_level";
	public static String VIDEO_CATEGORY = "video_category";
	public static String ENABLE_LIVE_CONNECTING_INDICATOR = "enable_live_connecting_indicator";
	public static String REPEATABLE = "repeatable";
	public static String REQUEST_RESULT = "request_result";
	public static String CALLBACK_CODE = "callback_code";
	public static String REPEATABLE_TASK = "repeatable_task";
	public static String USER_TOKEN = "user_token";
	public static String CHALLENGE_INITIAL_TIME = "initial_time";
	public static String CHALLENGE_BONUS_TIME = "bonus_time";
	public static String CHALLENGE_MIN_RATING = "min_rating";
	public static String CHALLENGE_MAX_RATING = "max_rating";
	public static String SAVED_COMPUTER_GAME = "saving";
	public static String USERNAME = "username";
	public static String PREF_COMPUTER_STRENGTH = "strength";
	public static String PREF_ACTION_AFTER_MY_MOVE = "aim";
	public static String USER_PREMIUM_STATUS = "premium_status";
	public static String PREF_SOUNDS = "enableSounds";
	public static String PREF_SHOW_SUBMIT_MOVE_LIVE = "ssblive";
	public static String PREF_SHOW_SUBMIT_MOVE = "ssb";
	public static String PREF_NOTIFICATION = "notifE";
	public static String PREF_BOARD_COORDINATES = "coords";
	public static String PREF_BOARD_SQUARE_HIGHLIGHT = "highlights";
	public static String PREF_BOARD_TYPE = "board";
	public static String PREF_PIECES_SET = "pieces";
	public static String FULLSCREEN_AD_ALREADY_SHOWED = "fullscreen_ad_showed";
	public static String ONLINE_GAME_LIST_TYPE = "gamestype";
	public static String USER_SESSION_ID = "user_session_id";
	public static String FIRST_TIME_START = "first_time_start";
	public static String START_DAY = "start_day";
	public static String LAST_ACTIVITY_PAUSED_TIME = "last_activity_aause_time";
	public static String ADS_SHOW_COUNTER = "ads_show_counter";
	public static String WHITE_USERNAME = "white_username";
	public static String BLACK_USERNAME = "black_username";

	public static String ACTION_SHOW_GAME_END_POPUP = "com.chess.lcc.android-show-game-end-popup";
}
